[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_presale_factory = "9eNoMwnzGs7FCEMD4RscEGgfCGJmbwDme9bAKNPXjyNy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solanaPresaleFactory.ts"
